#!/usr/bin/env python3

all = (
    "album",
    "albumartist",
    "albumartistsort",
    "artist",
    "artists",
    "artistsort",
    "barcode",
    "catalognumber",
    "date",
    "discnumber",
    "disctotal",
    "label",
    "media",
    "musicbrainz_albumartistid",
    "musicbrainz_albumid",
    "musicbrainz_artistid",
    "musicbrainz_releasegroupid",
    "musicbrainz_releasetrackid",
    "musicbrainz_trackid",
    "originaldate",
    "originalyear",
    "releasecountry",
    "releasestatus",
    "releasetype",
    "replaygain_album_gain",
    "replaygain_album_peak",
    "replaygain_track_gain",
    "replaygain_track_peak",
    "script",
    "title",
    "totaldiscs",
    "totaltracks",
    "tracknumber",
    "tracktotal",
)

album = {
    "artist": "albumartist",
    "album": "album",
    "type": "releasetype",
    "year": "originalyear",
    "total_tracks": "tracktotal",
    "total_discs": "disctotal",
    "label": "label",
    "catalog_number": "catalognumber",
}

track = {
    "track_number": "tracknumber",
    "track_title": "title",
    "disc": "discnumber",
}

example = (
    [
        ("releasecountry", ["US"]),
        ("replaygain_track_peak", ["1.000000"]),
        ("script", ["Latn"]),
        ("discnumber", ["1"]),
        ("replaygain_album_gain", ["-9.60 dB"]),
        (
            "musicbrainz_releasegroupid",
            ["06ae0024-2bef-36ff-ad38-a5d2604e0771"],
        ),
        ("replaygain_album_peak", ["1.000000"]),
        ("disctotal", ["1"]),
        ("originalyear", ["2003"]),
        ("label", ["Tzadik"]),
        ("date", ["2003"]),
        ("artist", ["Kayo Dot"]),
        ("artistsort", ["Kayo Dot"]),
        ("tracktotal", ["5"]),
        ("media", ["CD"]),
        ("totaltracks", ["5"]),
        ("musicbrainz_albumid", ["cec35abb-55a3-4634-84d6-50870f2faea7"]),
        ("barcode", ["702397709220"]),
        (
            "musicbrainz_releasetrackid",
            ["88ddb2ed-6250-4f94-b912-3e732f9dc629"],
        ),
        ("catalognumber", ["TZ 7092"]),
        ("totaldiscs", ["1"]),
        ("albumartist", ["Kayo Dot"]),
        ("originaldate", ["2003-10-23"]),
        ("album", ["Choirs of the Eye"]),
        ("releasetype", ["album"]),
        ("releasestatus", ["official"]),
        ("artists", ["Kayo Dot"]),
        ("title", ["The Antique"]),
        ("albumartistsort", ["Kayo Dot"]),
        (
            "musicbrainz_albumartistid",
            ["3979eee5-c72a-4b0a-9191-a0243881250a"],
        ),
        ("tracknumber", ["5"]),
        ("musicbrainz_trackid", ["23ebf60a-d8bc-47a1-9bd8-7e3ebc1f5def"]),
        ("musicbrainz_artistid", ["3979eee5-c72a-4b0a-9191-a0243881250a"]),
        ("replaygain_track_gain", ["-9.66 dB"]),
    ],
)
