#!/usr/bin/env python3

APP_NAME = "MusicLists"
VERSION = "0.1"

QUIET = False
VERBOSE = False
DEBUG = False

INCLUDE_NONE = False
NO_TRACKLIST = False
DEDUP = True
ONLY_HIGHEST_MATCH = True

ALBUM_MAX_SCORE = None
ALBUM_MIN_SCORE = None
TRACK_MAX_SCORE = None
TRACK_MIN_SCORE = None
MAX_RATINGS = None
MIN_RATINGS = None

KEY_LENGTH = 14
KEY_SEP = "-"

AUTO_FIELD = "possible"
VERIFIED_FIELD = "verified"
DATA_SUFFIX = "polars"
TEXT_SUFFIX = "txt"

MIN_LEVEL = 1
MAX_LEVEL = 4
